name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go:
          - "1.16"
          - "1.15"
          - "1.14"
          - "1.13"
          - "1.12"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Lint code
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -v --timeout=5m
      - name: Testing
        run: |
          make test
      - name: Coverage
        run: |
          make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
